name: flutter_playground
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get: ^4.6.5
  get_storage: ^2.0.3
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  jwt_decoder: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.1
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  http_mock_adapter: ^0.3.3
flutter:
  uses-material-design: true
